### ISSUE TITLE
Как пройти пятый уровень?

### ISSUE THREAD

**Issue by pyshcoder** [gbdrm/HabraQuest#1]
RO на хабре, пишу тут

**Comment by gbdrm** [comment]
все написано в задании. и ответ тоже.

**Comment by pyshcoder** [comment]
Да я понимаю, но сколько не бился, не могу понять логики

**Comment by gbdrm** [comment]
ну я в прямом смысле - ответ же написан в задании. Так и написан, прямым текстом.

**Comment by pyshcoder** [comment]
Черт подери, действительно, как я сразу то не додумался...
